spring:

  profiles:
    active: dev

  application:
    resource: C:/Users/WAC/Dysk Google
#    "C:\\Users\\WAC\\Dysk Google"

  datasource:
    url: jdbc:postgresql://localhost/domo_db
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

---

spring:
  profiles: local

  mail:
    host: smtp.gmail.com
    port: 587
    username: adamwojak88@gmail.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          from: adamwojak88@gmail.com
          replyTo: adam.wojak@wp.eu

---

spring:
  profiles: dev

  mail:
    host: smtp.wp.pl
#    zalecany port przez wp.pl to: 465, działa natomiast: 587
    port: 587
    username: adamwoj10@wp.pl
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          ssl: true
          starttls:
            enable: true
            required: true
          from: adamwoj10@wp.pl
          replyTo: adamwoj10@wp.pl
